### ISSUE TITLE
[FR] Add multiple user support

### ISSUE THREAD

**Issue by hiddify-com** [ihciah/shadow-tls#107]
This feature can be easily implemented by adding server password and user password and xor user password  and server password.

Therefore, in the server side we can easily identify the user

**Comment by kekomenos** [comment]
> This feature can be easily implemented by adding server password and user password and xor user password and server password.
> 
> Therefore, in the server side we can easily identify the user

**Comment by OmlineEditor** [comment]
In version 3 this is already implemented
