### ISSUE TITLE
哈喽新年好，我在安装后，CPU提示占用率100%不知道怎么回事

### ISSUE THREAD

**Issue by kankankankankankan** [ihciah/shadow-tls#109]
使用的工具为Finalshell,停止服务占用就恢复正常
![2024-02-13 at 15 33@2x](https://github.com/ihciah/shadow-tls/assets/11487346/d6936dde-bb94-43f7-8004-3faacca505a0)

**Comment by lesswest** [comment]
Environment=MONOIO_FORCE_LEGACY_DRIVER=1

**Comment by betterdoitnow** [comment]
Debian 11， 编辑 /etc/profile ，增加一行 export MONOIO_FORCE_LEGACY_DRIVER=1，重启之后，还是一样finalshell CPU显示100%.

**Comment by JasonSCSE** [comment]
On Debian 11, try to use some old core version

**Comment by love4taylor** [comment]
高版本内核加上使用 io_uring 导致的 iowait 高，参考 https://bbs.archlinux.org/viewtopic.php?id=287343

> Debian 11， 编辑 /etc/profile ，增加一行 export MONOIO_FORCE_LEGACY_DRIVER=1，重启之后，还是一样finalshell CPU显示100%.

不是这么用的，MONOIO_FORCE_LEGACY_DRIVER 要加在启动服务里，比如 systemd

```
[Unit]
After=network.target

[Service]
Type=simple
DynamicUser=yes
AmbientCapabilities=CAP_NET_BIND_SERVICE
LimitNOFILE=32768
LimitMEMLOCK=infinity
Environment=RUST_LOG=error
Environment=MONOIO_FORCE_LEGACY_DRIVER=1
ExecStart=/usr/bin/shadow-tls config --config /etc/shadow-tls.json
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by kankankankankankan** [comment]
> 高版本内核加上使用 io_uring 导致的 iowait 高，参考 https://bbs.archlinux.org/viewtopic.php?id=287343
> 
> > Debian 11， 编辑 /etc/profile ，增加一行 export MONOIO_FORCE_LEGACY_DRIVER=1，重启之后，还是一样finalshell CPU显示100%.
> 
> 不是这么用的，MONOIO_FORCE_LEGACY_DRIVER 要加在启动服务里，比如 systemd
> 
> ```
> [Unit]
> After=network.target
> 
> [Service]
> Type=simple
> DynamicUser=yes
> AmbientCapabilities=CAP_NET_BIND_SERVICE
> LimitNOFILE=32768
> LimitMEMLOCK=infinity
> Environment=RUST_LOG=error
> Environment=MONOIO_FORCE_LEGACY_DRIVER=1
> ExecStart=/usr/bin/shadow-tls config --config /etc/shadow-tls.json
> Restart=always
> 
> [Install]
> WantedBy=multi-user.target
> ```

感谢用您的方法已经解决！
