### ISSUE TITLE
长时间压力测试下会留存大量空闲的TCP连接

### ISSUE THREAD

**Issue by HynoR** [ihciah/shadow-tls#12]
长时间运行后建立的连接数会越来越多并占用网络缓冲区内存，估计希望有主动设置连接超时的类似功能
![image](https://user-images.githubusercontent.com/20227709/192101719-05def34f-9ded-4f7f-93e1-33d3bfe45d8b.png)
![image](https://user-images.githubusercontent.com/20227709/192101537-a97a088c-6a53-44fb-9b46-eb591a361bdf.png)

**Comment by ihciah** [comment]
当前有设置 keepalive，但是只单向设置了，后续会优化。感谢反馈。

**Comment by ihciah** [comment]
可以尝试下最新版本吗？应该已经fix了。
ps：新版本有不兼容改动，主要是启动参数上的改动。

**Comment by HynoR** [comment]
0.21新版在转发ShadowsocksR的时候存在无法正常转发的情况，0.14没有这个问题

0.21使用的的命令
./stlsv2 client --listen 0.0.0.0:34009 --server 1.1.1.1(海外ip):4639 --sni www.apple.com.cn --password  a9f32k
./stlsv2 server --listen 0.0.0.0:4639 --server 127.0.0.1(目的地):21002 --tls www.apple.com.cn:443 --password a9f32k

0.14使用的的命令
./stlsv1 client  0.0.0.0:34009  1.1.1.1(海外ip):4639  www.apple.com.cn 
./stlsv1 server  0.0.0.0:4639  127.0.0.1(目的地):21002 www.apple.com.cn:443

如果需要tcpdump或者其他调试信息我可以方便去弄

**Comment by ihciah** [comment]
是部分不正常吗？我这里配合 ss 使用可以正常工作（现在就在使用）。
我不确定是不是 tls1.3 的问题，可以帮我试试换个 tls1.2 的域名是不是能正常工作。
如果不能麻烦帮忙抓下包发我邮箱 谢谢

**Comment by HynoR** [comment]
排除SSR协议的问题,换SS依然不能用0.20正常转发。
异常主要表现为流量没有即时转发到目的地，用Clash的延迟测试 访问 gstatic.com 或者其他网站啥的，只有部分请求到达了SS后端（类似高丢包的状态），但是shadow-tls两端的日志均为正常转发，应该有可能是sni的问题，目前不太清楚用啥sni能tls1.2

开了个临时环境做了下 tcpdump: 
https://mega.nz/file/tp8m3QoK#_qJT05BWF8jkWU7ODUDL_9IFAbInYa5CJnVAW2uzmaA

**Comment by ihciah** [comment]
可以试试调下代码里的 log level 为 DEBUG 再看日志

**Comment by ihciah** [comment]
> 排除SSR协议的问题,换SS依然不能用0.21正常转发。 异常主要表现为流量没有即时转发到目的地，用Clash的延迟测试 访问 gstatic.com 或者其他网站啥的，只有部分请求到达了SS后端（类似高丢包的状态），但是shadow-tls两端的日志均为正常转发，应该有可能是sni的问题，目前不太清楚用啥sni能tls1.2
> 
> 开了个临时环境做了下 tcpdump: https://mega.nz/file/tp8m3QoK#_qJT05BWF8jkWU7ODUDL_9IFAbInYa5CJnVAW2uzmaA

看了下包，没太看出来问题233
可以用腾讯云的试下，不过我这边用 www.apple.com.cn 也表现正常的。。

**Comment by zhenpingfeng** [comment]
recommend using tracing_subscriber::EnvFilter instead of hardcoded with_max_level.

**Comment by HynoR** [comment]
> > 排除SSR协议的问题,换SS依然不能用0.21正常转发。 异常主要表现为流量没有即时转发到目的地，用Clash的延迟测试 访问 gstatic.com 或者其他网站啥的，只有部分请求到达了SS后端（类似高丢包的状态），但是shadow-tls两端的日志均为正常转发，应该有可能是sni的问题，目前不太清楚用啥sni能tls1.2
> > 开了个临时环境做了下 tcpdump: https://mega.nz/file/tp8m3QoK#_qJT05BWF8jkWU7ODUDL_9IFAbInYa5CJnVAW2uzmaA
> 
> 看了下包，没太看出来问题233 可以用腾讯云的试下，不过我这边用 [www.apple.com.cn](http://www.apple.com.cn) 也表现正常的。。

好的 我再测试一下

**Comment by ihciah** [comment]
Closed due to inactivity. If the problem persists, please reopen it.
