### ISSUE TITLE
请问，如果浏览器直接访问会发生什么？

### ISSUE THREAD

**Issue by JarmoHu** [ihciah/shadow-tls#13]
请问，如果浏览器直接访问会发生什么？能访问到伪装的网站上吗？

**Comment by ihciah** [comment]
不会，目前没有对主动探测的防御，后续会考虑添加。

**Comment by artcaster** [comment]
建议添加，对转发的探测访问限速

**Comment by ihciah** [comment]
已实现。
在客户端强制解析的情况下，直接浏览器打开可以正常访问握手服务对应网页。

**Comment by artcaster** [comment]
666,能对伪装的网站限速和限制流量吗

**Comment by ihciah** [comment]
> 666,能对伪装的网站限速和限制流量吗

目前没这功能，没必要吧感觉。

**Comment by kousyougi** [comment]
> 已实现。 在客户端强制解析的情况下，直接浏览器打开可以正常访问握手服务对应网页。

我實際測試，原始網頁還是跑不出來。

![log](https://user-images.githubusercontent.com/43228565/193730627-f48acb90-53d8-455d-9c94-b39586425737.jpg)


```
2022-10-04T03:44:01.819340Z  INFO shadow_tls: Server is running!
Listen address: 0.0.0.0:443
Remote address: 127.0.0.1:23799
TLS server address: cloud.tencent.com:443
```

**Comment by ihciah** [comment]
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/1707505/193732436-d06f2571-5503-40fe-bbe7-e612079943d0.png">

emmmm 有点迷，我这边好像还挺正常的，浏览器也是 OK 的。

**Comment by kousyougi** [comment]
> <img alt="image" width="1784" src="https://user-images.githubusercontent.com/1707505/193732436-d06f2571-5503-40fe-bbe7-e612079943d0.png">
> 
> emmmm 有点迷，我这边好像还挺正常的，浏览器也是 OK 的。

我用curl指令在遠端的電腦測試好像是正常的。也有刷出下面內容。
但開edge跟chrome都顯示 ERR_SSL_PROTOCOL_ERROR

```
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
> GET / HTTP/1.1
> Host: cloud.tencent.com
> User-Agent: curl/7.83.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 04 Oct 2022 04:37:09 GMT
< Content-Type: text/html; charset=utf-8
< Vary: Accept-Encoding
< x-req-id: HkR_ONFzi
< Set-Cookie: qcmainCSRFToken=SylCd_VYfi; Domain=.cloud.tencent.com; Path=/
< Set-Cookie: intl=; Domain=.cloud.tencent.com; Path=/; Secure
< Set-Cookie: language=zh; Max-Age=15552000; Domain=.cloud.tencent.com; Path=/; Expires=Sun, 02 Apr 2023 04:37:09 GMT
< X-Cache-Lookup: Cache Miss
< Content-Length: 173361
< X-NWS-LOG-UUID: 13498345149178432078
< Connection: keep-alive
< X-Cache-Lookup: Cache Miss
<
<!DOCTYPE html>
<html lang="zh">
<head>
```

**Comment by ihciah** [comment]
emm，可以 F12 看下解析出来的地址符不符合预期。

**Comment by kousyougi** [comment]
查到原因了。用舊版ie顯示是正常的。
可能edge跟chrome有在偷偷比對domain name 跟ip 有沒有相符。

**Comment by ihciah** [comment]
> 

应该没有这种逻辑，有可能我这边实现有点问题。方便的话帮我抓个包看下？

**Comment by kousyougi** [comment]
> > 
> 
> 应该没有这种逻辑，有可能我这边实现有点问题。方便的话帮我抓个包看下？

我不會抓包哩。
但剛剛另外測試，把shadows-tls關掉，在server端單純用nginx轉發TCP。
chrome跟edge可以正常顯示原網頁的。所以跟domain name和IP無關。

nginx.conf
```
stream {
    upstream us {
        server 43.152.54.219:443;
    }
    server {
        listen 443;
        proxy_pass us;
    }
}
```

**Comment by artcaster** [comment]
还是希望加上伪装网站的限速限流量功能，如果被别人怀疑是代理，当反代来刷流量很容易超过vps流量配额，就是有像什么黑🦅之类的人扫扫扫然后攻击

**Comment by ihciah** [comment]
> 还是希望加上伪装网站的限速限流量功能，如果被别人怀疑是代理，当反代来刷流量很容易超过vps流量配额，就是有像什么黑🦅之类的人扫扫扫然后攻击

这样会成为新的特征；而且需要加入统计功能，需要维护历史数据，都会增加复杂度，不再纯粹了。

**Comment by kousyougi** [comment]
> 还是希望加上伪装网站的限速限流量功能，如果被别人怀疑是代理，当反代来刷流量很容易超过vps流量配额，就是有像什么黑🦅之类的人扫扫扫然后攻击

目前沒有看到v2ray或trojan幫偽裝網站做流量控制。有點沒必要，還讓原本不寬裕的CPU資源雪上加霜。
你很想加的話，可以自己用iptables指令限制流量，就一行指令而已。

**Comment by JarmoHu** [comment]
> > 还是希望加上伪装网站的限速限流量功能，如果被别人怀疑是代理，当反代来刷流量很容易超过vps流量配额，就是有像什么黑🦅之类的人扫扫扫然后攻击
> 
> 这样会成为新的特征；而且需要加入统计功能，需要维护历史数据，都会增加复杂度，不再纯粹了。

提供一个iptables或者nftables管理脚本就好了
