### ISSUE TITLE
期待能出编译好的linux客户端和服务端，直接在环境中运行

### ISSUE THREAD

**Issue by zhezhe168** [ihciah/shadow-tls#14]

**Comment by HynoR** [comment]
release里不是有...

**Comment by zhezhe168** [comment]
看到了。。。大佬可以写下usage用法么，docker不熟有点累

**Comment by ihciah** [comment]
有这么几个参数：
1. 第一个参数是 mode: `client` 或 `server`，对应客户端或服务端的运行模式。
2. 第二个参数是 listen: 表示监听的地址，比如 `0.0.0.0:443`。
3. 第三个参数是 server: 表示远端服务器地址，对于 client 侧来说，填写 server 地址即可，比如 `1.2.3.4:443`；对于 server 侧来说，填写目标服务地址，比如本机部署的 ss `127.0.0.1:8443`。
4. 第四个参数的 tls: 对于 client 侧来说，填写你预期的 SNI，比如 `cloud.tencent.com`，纯域名，不带端口号；对于 server 侧来说，填写目标握手服务地址，带端口号，比如 `cloud.tencent.com:443`，直接写 `ip:port` 也是可以的。

**Comment by ihciah** [comment]
在 --help 里添加了参数说明。
