### ISSUE TITLE
Zero Copy may destroy the confusing nature?

### ISSUE THREAD

**Issue by ertuil** [ihciah/shadow-tls#15]
In SSL/TLS, every packet is wrapped in a special **Record Protocol**, where the first byte is in 20-23. By adopting the zero-copy technology and directly relay TCP contents, it seems that it is easy to discover a `shadow-tls` connection by just checking the first byte of the first packet after Handshake.

**Comment by ihciah** [comment]
Yes in fact it is. So in the long term, the application data packing need to be implemented.

**Comment by ertuil** [comment]
Get it. Then, it might be a novel way of thinking about design protocols.

**Comment by ihciah** [comment]
I have an idea now and maybe it will be implemented next week.

**Comment by ihciah** [comment]
V2 protocol updated.
