### ISSUE TITLE
是否可以理解成一个端口转发工具？

### ISSUE THREAD

**Issue by LiHang941** [ihciah/shadow-tls#16]
#通过client连接server，其他客户端用ss连接client监听的端口，sever转发到对应的接受ss流量的服务

**Comment by LiHang941** [comment]
谢谢大佬，解决了sni阻断的问题，现在很爽

**Comment by ihciah** [comment]
是的，就是这个意思。
可以尝试下新版，流量更难以辨识，且抗主动探测。

**Comment by ihciah** [comment]
https://www.ihcblog.com/a-better-tls-obfs-proxy/

**Comment by LiHang941** [comment]
谢谢大佬，等假期结束试试
