### ISSUE TITLE
docker运行失败OutOfMemory,

### ISSUE THREAD

**Issue by pyooyq** [ihciah/shadow-tls#18]
系统是Debian11
错误日志：
2022-10-03T09:20:47.158302Z  INFO shadow_tls: Started with parallelism 1
thread '<unnamed>' panicked at 'unable to build monoio runtime: Os { code: 12, kind: OutOfMemory, message: "Out of memory" }', src/main.rs:82:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

当时内存占用情况：
MiB Mem :    473.3 total,    218.8 free,    131.6 used,    122.9 buff/cache
MiB Swap:    256.0 total,    217.4 free,     38.6 used.    327.0 avail Mem

**Comment by ihciah** [comment]
参考这里 https://github.com/bytedance/monoio/blob/master/docs/zh/memlock.md 修改限制，或添加 MONOIO_FORCE_LEGACY_DRIVER=1 环境变量强制使用 epoll 作为后端驱动。

**Comment by pyooyq** [comment]
> 参考这里 https://github.com/bytedance/monoio/blob/master/docs/zh/memlock.md 修改限制，或添加 MONOIO_FORCE_LEGACY_DRIVER=1 环境变量强制使用 epoll 作为后端驱动。

感谢回复，解决了
