### ISSUE TITLE
question:代理检测

### ISSUE THREAD

**Issue by ruokeqx** [ihciah/shadow-tls#20]
你好，感觉你这个挺有趣的，看了一下你的blog和协议文档，但是我对隐藏和检测这方面不是很了解，直观感觉是下面这样你的这个协议就不能用了吧（会存在这种检测可能吗 感觉小型网络是可能的）
```
if net.LookupIP(handshake_domain) != ip {
    ban(ip)
}
```

**Comment by ihciah** [comment]
大型网站一般用 CDN，而 CDN 节点太多了。比如你用了 cloudflare 的服务，那么 cf 的所有 ip 理论上都能用(anycast)，但实际上你只会解析出来几个 ip。
