### ISSUE TITLE
How to disable password obfuscation?

### ISSUE THREAD

**Issue by maskedeken** [ihciah/shadow-tls#26]

**Comment by ihciah** [comment]
Why disable? If you set a widely used password(for example empty password) then it can be detected.

**Comment by ArcCal** [comment]
大佬们，Shadow-TLS不用docker部署可以吗，求分享示例配置文件

**Comment by ihciah** [comment]
> 大佬们，Shadow-TLS不用docker部署可以吗，求分享示例配置文件

可以 `./shadow-tls --help`、`./shadow-tls client --help`、`./shadow-tls server --help` 看到参数说明。

**Comment by ArcCal** [comment]
> > 大佬们，Shadow-TLS不用docker部署可以吗，求分享示例配置文件
> 
> 可以 `./shadow-tls --help`、`./shadow-tls client --help`、`./shadow-tls server --help` 看到参数说明。

还是没搞懂 shadowtls是可以自己独立作为代理工具呢还是必须依靠或者配合其他的才可以

**Comment by ArcCal** [comment]
--server <SERVER_ADDR>    Your data server address(like 127.0.0.1:8080)

这个选项是干啥的呢

**Comment by rockyzhng** [comment]
> Why disable? If you set a widely used password(for example empty password) then it can be detected.

那shadowtls的tls只用来握手吗？不用来封装shadowsocks流量？如果用的tls封装后，那ss的本来加密就没有必要了啊。不用封装怎么能类比trojan呢？

**Comment by ihciah** [comment]
The password is only used for authencation, not encryption.

rockyzhng ***@***.***>於 2022年11月17日 週四，下午5:46寫道：

**Comment by rockyzhng** [comment]
> The password is only used for authencation, not encryption. rockyzhng ***@***.***>於 2022年11月17日 週四，下午5:46寫道：
> […](#)
意思就是用tls封包的咯，那shadowsocks的加密方法是不是可以选择none，只保留密码授权验证呢？这样就不用双重解密，提高性能，反正外面有tls加密。

**Comment by rockyzhng** [comment]
看到作者的说明了：这个服务需要双边部署，并且它一般需要搭配一个加密代理（因为本项目不包含数据加密和代理请求封装功能，这不是我们的目标）。

不对数据包进行tls封装。

**Comment by ihciah** [comment]
Closed. If need more disscussion, feel free to reopen it.
