### ISSUE TITLE
Won't close fd cause "Too many open files (os error 24)"

### ISSUE THREAD

**Issue by zhenpingfeng** [ihciah/shadow-tls#3]
shadow-tls won't close the file handles after the connection is used. finally, it will cause "Too many open files (os error 24)" Error.

**Comment by zhenpingfeng** [comment]
https://github.com/tokio-rs/tokio/issues/4782 
seem same as this tokio's issue

**Comment by ihciah** [comment]
Aha, I also observed the same problem. There are significantly more logs for creating connections than closing connections.
And I think this problem has no relation with tokio. It's just my mistake that I did not relay the half close action. I've pushed a fix and let's check if it will work as expected.

**Comment by zhenpingfeng** [comment]
![image](https://user-images.githubusercontent.com/13215166/186948115-7f767397-d152-43fc-a3c3-7cab8bb73af0.png)
looks fine, closed
