### ISSUE TITLE
会有支援http2计划吗?

### ISSUE THREAD

**Issue by kingwilliam** [ihciah/shadow-tls#32]
会有支援http2计划吗?

因测试时发现shadow-tls client 和 server 之间不停建立tcp connection, 看似没有h2的多路复用特征

**Comment by ihciah** [comment]
shadow-tls目前作为tcp wrapper工作。
不停建立连接是ss的行为，需要多路复用可以换用其他支持的底层代理实现，再用shadow-tls包装。

**Comment by kingwilliam** [comment]
明白 我試試 謝謝
