### ISSUE TITLE
0.2.3 客户端报错

### ISSUE THREAD

**Issue by ylx2016** [ihciah/shadow-tls#34]
thread '<unnamed>' panicked at 'client exited: invalid dns name', src/main.rs:125:14

./stls -t 1 client --server "sever:443" --sni "cloud.tencent.com:443" --password "password" --listen "0.0.0.0:18080"

**Comment by ihciah** [comment]
sni不要带端口

dr ***@***.***>於 2022年10月20日 週四，下午12:20寫道：
