### ISSUE TITLE
Cdn

### ISSUE THREAD

**Issue by Rahattt** [ihciah/shadow-tls#35]
hello, is it possible to use Shadow Tls v2 via CDN?

**Comment by ihciah** [comment]
If CDN support TCP proxy, then yes. However, most of them do not support L4 proxy.
Since shadow-tls does not work on L7, so most of CDNs not support it. It is a TCP wrapper.

**Comment by ihciah** [comment]
What I know is Cloudflare not support it.

**Comment by ihciah** [comment]
Closed due to inactivity. If the problem persists, please reopen it.
