### ISSUE TITLE
Support SIP003

### ISSUE THREAD

**Issue by s7lx** [ihciah/shadow-tls#39]
https://shadowsocks.org/guide/sip003.html
If this feature is supported, the product will become easier to use

**Comment by ihciah** [comment]
Indeed it is... Does anyone want to implement it? I will be very grateful.

**Comment by kirito41dd** [comment]
let me try a try(

**Comment by ihciah** [comment]
Thanks to @kirito41dd this feature is implemented! This issue will be closed. 
If need more disscussion, feel free to reopen it.
