### ISSUE TITLE
希望能增加一个树莓派的版本

### ISSUE THREAD

**Issue by zijingliumiranda** [ihciah/shadow-tls#40]
Linux raspberrypi 5.10.63-v7l  armv7l GNU/Linux

**Comment by ArcCal** [comment]
shadow-tls-aarch64-unknown-linux-musl就是树莓派的版本

**Comment by zijingliumiranda** [comment]
试了一下
bash: ./shadow-tls-aarch64-unknown-linux-musl: cannot execute binary file: Exec format error
查了一下，可能是因为树莓派是32位系统的原因吧

**Comment by ihciah** [comment]
预编译版本已添加 armv7 target，等待 github 自动构建即可（当然你也可以自行构建）。

**Comment by hzww** [comment]
新版的 log 可以在 systemctl status 下显示了，但是 --version 显示的还是 0.2.3

**Comment by ihciah** [comment]
> 新版的 log 可以在 systemctl status 下显示了，但是 --version 显示的还是 0.2.3

忘了改，问题不大 :)

**Comment by ihciah** [comment]
Closed. If need more disscussion, feel free to reopen it.
