### ISSUE TITLE
客户端报错

### ISSUE THREAD

**Issue by zijingliumiranda** [ihciah/shadow-tls#41]
最新树莓派客户端：
2022-11-14T00:46:13.416959Z ERROR rustls::conn: TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: HandshakeFailure,

在windows上使用WSL2的ubuntu,也是相同的报错

但是在ios上的shadowrocket上使用正常，配置是ss+shadows_tls
使用的sni是apple.com

不知道是哪里出了问题

**Comment by zijingliumiranda** [comment]
> > 最新树莓派客户端： 2022-11-14T00:46:13.416959Z ERROR rustls::conn: TLS alert received: AlertMessagePayload { level: Fatal, description: HandshakeFailure,
> > 在windows上使用WSL2的ubuntu,也是相同的报错
> > 但是在ios上的shadowrocket上使用正常，配置是ss+shadows_tls 使用的sni是apple.com
> > 不知道是哪里出了问题
> 
> 小火箭怎么配ss+shadows_tls的客户端？ 能不能给个例子 混淆要改吗

https://github.com/ihciah/shadow-tls/issues/29

**Comment by sjtuross** [comment]
跟楼上一样的配置，不行。小火箭日志中有一堆这个错`[10:21:44.944] shadowsocks decrypt error`

**Comment by ihciah** [comment]
可以试下使用墙内/内网服务器启动 client，之后使用裸 ss 协议连接。

**Comment by ihciah** [comment]
Closed due to inactivity. If the problem persists, please reopen it.
