### ISSUE TITLE
在使用youtube客户端时，视频卡住，经常要等很久才能播放

### ISSUE THREAD

**Issue by endsock** [ihciah/shadow-tls#43]
怀疑时quic的问题，iptables禁用了udp 80，443没有效果，clash禁用了udp也没有效果。
为了排除shadow-tls的问题，采用clash直接链接shadowsocks-rust，不禁用udp 80，443，不禁用clash udp，用客户端看视频没问题，非常流畅
当clash->shadow-tls client->shadow-tls server->shadowsocks-rust，不禁用udp 80，443，不禁用clash udp，用客户端看视频卡住超时，等很久后才开始播放，换一个视频又卡住，等很久...，禁用udp 80，443，禁用clash udp，问题依旧
具体是哪里的问题说不上，但是套了shadow-tls就不正常，实测如此，作者可以试试

除了使用客户端看视频有问题外，访问网页，用网页看视频均没有问题

使用到的软件clash，shadow-tls，shadowsocks-rust均是最新版本
视频客户端使用的是：android youtube vanced

**Comment by endsock** [comment]
更新了youtube vanced版本之后问题修复

**Comment by ihciah** [comment]
shadowsocks-rust 用的什么协议呢？部分协议对包的大小有要求，不支持。可以找找之前的一个 issue。
如果是这个问题换协议就可以解决。

**Comment by endsock** [comment]
用的是原生ss协议

**Comment by endsock** [comment]
经过几天的使用，可能问题出在连接失效时的超时处理上，有时网页访问google也会出现类似问题，出现比较低频，不容易重现
