### ISSUE TITLE
OpenVPN over Shadow-tls

### ISSUE THREAD

**Issue by kalhori124** [ihciah/shadow-tls#48]
Hi,

I'v just tested OpenVPN over Shadow-tls, it works but OpenVPN client takes too much time to connect to the server and the Internet speed connection is very slow, about 1Mbps.

OpenVPN client => Shadow-tls client=>  GFW  => Shadow-tls server => OpenVPN server

**Comment by ihciah** [comment]
Hi! You can try our latest version and enable TCP_NODELAY.
In the next release we will make it default.

**Comment by ihciah** [comment]
The latest version enables TCP_NODELAY by default, you can try it.
Closed. If need more disscussion, feel free to reopen it.
