### ISSUE TITLE
咨询：shadowtls服务端如何使用中转服务器

### ISSUE THREAD

**Issue by joyoner** [ihciah/shadow-tls#50]
正常直连：client->shadowtls-sever
使用国内中转：client->国内端口转发->shadowtls-sever

想咨询一下，如果是第二种模式，中转机的端口应该转发到server的哪个端口。

**Comment by ihciah** [comment]
直接转发 shadow-tls server 暴露的端口即可。

**Comment by ihciah** [comment]
Closed due to inactivity. If the problem persists, please reopen it.
