### ISSUE TITLE
Multiple SNI

### ISSUE THREAD

**Issue by hichkak** [ihciah/shadow-tls#51]
Thank you for your wonderful software.
Is it possible to use multiple SNI ?

**Comment by ihciah** [comment]
Now we don't support it. Is there some reasons for using multiple SNIs?

If we support it, we may have to allow users custom selection strategy like a load balancer. For example random, but is it really help anti-detection?

**Comment by hichkak** [comment]
Something like port hopping will do, for now I run multiple instances.

**Comment by hichkak** [comment]
It can be both, using a single sni can put it a risk of detection,
switching in between multiple SNIs might help them stay unfiltered.

**Comment by ihciah** [comment]
Multiple SNI is supported now.

**Comment by hichkak** [comment]
Thank you very much
