### ISSUE TITLE
每次打开都会“无法访问此网站”

### ISSUE THREAD

**Issue by onlyJinx** [ihciah/shadow-tls#58]
然后隔了几秒后chrome会自动刷新网页后才正常进去网站。当打开后重复打开其他页面（同一个域名）就都可以正常打开，如果一个网站第一次打开的话基本都是提示无法访问，是第一次访问网站是解析DNS的问题吗？

用的是shadow-tls和shadowsocks-rust

代理环境是debian11里运行以上软件然后对外提供 socks 1080端口，chrome里用  --proxy-server=socks5://192.168.1.XX:1080 来连接代理，dns解析应该都是远程解析的。

![image](https://user-images.githubusercontent.com/21324835/211487318-45d1e217-073d-4ded-9ec8-107496f880bc.png)

![image](https://user-images.githubusercontent.com/21324835/211487412-feb7326c-7a20-4970-a41d-950620539584.png)

**Comment by ihciah** [comment]
Seems dup with #31.

shadowsocks-rust 并不是纯粹的面向流的协议，它对单个 tcp 数据包有要求。而 shadow-tls 是面向流的代理，并不保证包的完全一致。
一个可选方案是切到原版 shadowsocks。

**Comment by onlyJinx** [comment]
是建议使用libev吗？另外再问一句，因为流量外面本身已经有一层tls加密保护着，所以内部那一层ss的加密是不是就不是特别重要了？

**Comment by ihciah** [comment]
> 是建议使用libev吗？另外再问一句，因为流量外面本身已经有一层tls加密保护着，所以内部那一层ss的加密是不是就不是特别重要了？

是的。
shadow-tls并不提供流量加密和请求封装，所以仍需要shadowsocks提供这两个能力。但不再需要除这两个之外的能力，比如混淆等。反倒是特地伪装成某些协议会导致容易识别。所以这里推荐shadowsocks，是因为它的协议刚好满足这些。

**Comment by onlyJinx** [comment]
好的，多谢解答
