### ISSUE TITLE
Some simple issues

### ISSUE THREAD

**Issue by Xway0312** [ihciah/shadow-tls#6]
- Will Windows(amd-64) version be released?

- Is shadow-tls compatible with trojan/v2ray or such protocols?

- If the answer of former issue is 'Yes' , can you give the configuration files out?

Thanks.

**Comment by ihciah** [comment]
1. In short term, no.
2. No.

**Comment by Xway0312** [comment]
I see.

Best,
Xway

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
在 2022年8月29日 星期一 下午 7:07，ihc童鞋@提不起劲 ***@***.***> 寫道：

**Comment by nekohasekai** [comment]
sing-box has added support for shadow-tls:

https://sing-box.sagernet.org/examples/shadowtls/

**Comment by Xway0312** [comment]
> sing-box has added support for shadow-tls:
> 
> https://sing-box.sagernet.org/examples/shadowtls/

Whoa!
