### ISSUE TITLE
v0.2.9 can't start client service

### ISSUE THREAD

**Issue by alschw** [ihciah/shadow-tls#65]
Affect version: v0.2.9
Issue description: Updated to v0.2.9, client service couldn't start successfully.

Command:
shadow-tls client --listen 0.0.0.0:10000 --server 1.2.3.4:12345 --sni www.apple.com --password PASSWORD --alpn h2

Error messages:
thread 'main' panicked at 'Mismatch between definition and access of `tls_names`. Could not downcast to TypeId { t: 14004935008834332786 }, need to downcast to TypeId { t: 2276638344098854107 }
', /cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.4/src/parser/error.rs:30:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Additional message:
Same configuration, works OK with v0.2.8.

B.R.
Thanks

**Comment by ihciah** [comment]
Thanks for reporting.
This is an issue on args parsing. The bug is fix after v0.2.10.
Please wait until the build action finished, and update it.

**Comment by alschw** [comment]
> Thanks for reporting. This is an issue on args parsing. The bug affects client side, and fixed after v0.2.10. Please wait until the build action finished, and update it.

Test OK with v.0.2.11, thanks.
