### ISSUE TITLE
ARM下shadow-tls启动失败

### ISSUE THREAD

**Issue by bit1001** [ihciah/shadow-tls#7]
日志
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'unable to build monoio runtime: Os { code: 12, kind: OutOfMemory, message: "Out of memory" }', src/main.rs:46:18
thread '<unnamed>' panicked at 'unable to build monoio runtime: Os { code: 12, kind: OutOfMemory, message: "Out of memory" }', src/main.rs:46:18
2022-08-29T12:55:36.810718Z  INFO shadow_tls: Started with parallelism 4
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'unable to build monoio runtime: Os { code: 12, kind: OutOfMemory, message: "Out of memory" }unable to build monoio runtime: Os { code: 12, kind: OutOfMemory, message: "Out of memory" }', ', src/main.rssrc/main.rs::4646::1818

**Comment by ihciah** [comment]
mac or linux?

**Comment by bit1001** [comment]
> mac or linux?

#31~20.04.1-Ubuntu SMP Wed Jan 26 14:20:52 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by ihciah** [comment]
Try to adjust io-uring related settings according to monoio doc.

**Comment by ihciah** [comment]
Recently I updated the monoio runtime, you can try to set env `MONOIO_FORCE_LEGACY_DRIVER=1` to use legacy driver if you cannot make the `io_uring` work.

**Comment by ihciah** [comment]
不活跃 issue 我这边先关掉了，如果未接决可以 reopen
