### ISSUE TITLE
v2和trojan能搭配在一起用吗

### ISSUE THREAD

**Issue by shadow750d6** [ihciah/shadow-tls#72]
这是我们群里的讨论，请作者给个权威的答案

我的理解是，v2里，TLS application data只加了包头，没做其他处理，所以用trojan的话有明显特征（数据不随机）
群友都不同意我的说法

**Comment by shadow750d6** [comment]
还有v3可不可以？虽然有个xor，但是感觉挺弱的。

**Comment by ihciah** [comment]
v3版本的数据封装也没有加密，只有完整性校验。请确保数据是加密后的，看起来像乱码的东西。

**Comment by shadow750d6** [comment]
所以我是对的
