### ISSUE TITLE
浏览器直接访问服务器域名提示证书不安全？

### ISSUE THREAD

**Issue by ixxmu** [ihciah/shadow-tls#73]
部署了大佬的shadowtls，访问的目标服务器用的域名非IP，用浏览器打开域名，浏览器提示证书不安全，这个有什么影响么？

另外，隔壁的xray reality也是和shadowtls一样的功效么？ 

感谢大佬开发这么优秀的工具！

**Comment by ihciah** [comment]
强制解析域名到你自己的服务，在你服务端配置了这个域名的情况下，浏览器打开域名应该是可信的。提示证书不安全是不正常的。
xray reality 使用起来效果类似。

**Comment by ixxmu** [comment]
所以正确浏览器行为是，访问域名的时候，依旧是此域名证书下的网站，而不是跳转到白名单SNI的网址？

**Comment by ihciah** [comment]
没太理解你的意思，握手都没握上是没法跳转的。

**Comment by ixxmu** [comment]
结合大佬的回答和查找基本知道了，已用shadowTLS的sni分流解决，感谢大佬这么给力和易上手的工具👍
