### ISSUE TITLE
V3  parameters要怎么加？

### ISSUE THREAD

**Issue by yjps** [ihciah/shadow-tls#74]
![image](https://user-images.githubusercontent.com/32375607/220612211-210ff42c-7a19-40ba-a20a-445020c7680e.png)
V3  parameters
--v3 
--v3 1
--v3 = 1
都提示 `error: unexpected argument '--v3' found`

另外请问既然是tls连接，为什么示例 `shadow-tls --threads 1 server --listen 0.0.0.0:4430 --server 127.0.0.1:8888 --tls captive.apple.com --password 1` 使用4430端口，而不是用443端口呢？

**Comment by wansenlyt** [comment]
shadow-tls --threads 1 --v3 ……

**Comment by ihciah** [comment]
server 是 subcommand，v3 和 thread, disable_nodelay 都要加在 subcommand 之前。
（虽然我很想把 password 等公共参数也提出去，但有点破坏兼容性，先不动了。。）

**Comment by ihciah** [comment]
Closed. If need more disscussion, feel free to reopen it.
