### ISSUE TITLE
关于sni阻断？尝试使用v2和v3链接，首次链接能通，然后本地ip与服务器ip被阻断3分钟

### ISSUE THREAD

**Issue by moranno** [ihciah/shadow-tls#78]
各位有没有遇到过这样的问题：尝试使用v2和v3链接，首次链接能通，然后本地ip与服务器ip被阻断3分钟(无法ping通)，3分钟后ip被放出来，如果再次尝试链接，则再被阻断3分钟。注意只是针对本地IP与服务器IP的阻断，这时候用其他ping工具从全国其他地方ping服务器是通的。

请问可能是哪里的问题？

之前用trojan的时候也被sni阻断过，和上面的情况一模一样。
之前观察的结论：如果域名被加入sni阻断黑名单（或疑似名单），gfw会验证证书是否匹配sni，如果不匹配，则阻断。

> 名词说明：
> 阻断：ip阻断3分钟（无法ping通），3分钟后自动放出来，如果再有tls链接，继续阻断3分钟，周而复始。
> 老域名：用了1年的域名，疑似被加入黑名单。
> 新域名：注册了1年，一直没启用的新域名。
> 可信证书：通过可信CA申请的ecc证书。
> 客户端：clash
> sni：可在clash中配置sni(尝试使用www.gov.hk, www.icloud.com, 以及国内备案域名)
> 空sni：sni配置不填写内容
> 证书验证：可在客户端配置是否跳过证书验证，以配合sni
> 真实域名：申请了可信证书的域名，填入客户端服务器地址
> 
> 测试方法：（以下测试基于trojan tcp+tls：）
> 开始使用443端口，尝试使用高位端口同样引发阻断，换sni(尝试使用www.gov.hk, www.icloud.com, 以及国内备案域名)均引发阻断
> 只要带域名就会引发阻断，不管是真实域名还是sni
> 老域名+sni = 阻断
> ip(服务器只填入ip) + sni = 阻断
> ip + 空sni + 跳过证书验证 = 不阻断
> 新域名 + 老证书 + 空sni + 跳过证书验证= 阻断
> 新域名 + 新可信证书 + sni + 跳过证书 = 阻断
> 新域名 + 新可信证书 + 空sni + 不跳过证书 = 不阻断
> 新域名 + 新可信证书 + 空sni + 跳过证书验证 = 不阻断
> 老域名 + 老证书 + 新域名sni + 跳过证书验证 = 阻断 （验证sni与dns记录值是否比对）
> 老域名 + 新证书 + 新域名sni + 跳过证书验证 = 不阻断（验证sni与dns记录值是否比对）
> 
> 基于以上观察的基本结论：
> 如果域名被加入sni阻断黑名单（或疑似名单），gfw会验证证书是否匹配sni，如果不匹配，则阻断。

基于我上面的观察；shadowtls的使用应该是真实tls握手，为何会带来阻断问题呢？难道有其他可能的问题？

**Comment by moranno** [comment]
请 @gfw-report 和 @RPRX 来分析下可能造成这种阻断效果的原因？

**Comment by ihciah** [comment]
本地/远端 ip 命中标记后可能会有干扰，可以试着强制解析域名到你的 ip，然后测试是否浏览器访问正常。

**Comment by moranno** [comment]
> 本地/远端 ip 命中标记后可能会有干扰，可以试着强制解析域名到你的 ip，然后测试是否浏览器访问正常。

刚刚实验了reality协议，一样的发生了相同的阻断现象。
我猜测是因为我服务器地址填写的是IP，但TLS表演的却是www.bing.com；所以导致gfw无法获取sni，所以阻断。

如果shadowtls可以配置sni为TLS链接的www.bing.com，我想可以避免阻断。

**Comment by RPRX** [comment]
@moranno 你的猜测是错的

**Comment by moranno** [comment]
> @moranno 你的猜测是错的

可能sni阻断的原理很简单：中间人gfw验证证书中的域名如果与https访问的明文sni不相符（或没有sni），就阻断。

**Comment by xianren78** [comment]
可以称之为IP被当成CDN管理，CF和CFT的优选IP阻断也是这样阻断的。

**Comment by RPRX** [comment]
> > @moranno 你的猜测是错的
> 
> 可能sni阻断的原理很简单：中间人gfw验证证书中的域名如果与https访问的明文sni不相符（或没有sni），就阻断。

首先，[SNI 就是 www.bing.com](https://github.com/XTLS/Xray-core/issues/1767#issuecomment-1463307158)，专门给中间人看的，除非你配置了不发 SNI
其次，若你用 REALITY，它是 TLSv1.3，中间人看不到证书
最后，根据你的描述，[我认为是你的本地 IP 进运营商的黑名单了，我建议你换个运营商试试](https://github.com/XTLS/Xray-core/issues/1767#issuecomment-1463315288)

**Comment by ihciah** [comment]
> 本地/远端 ip 命中标记后可能会有干扰，可以试着强制解析域名到你的 ip，然后测试是否浏览器访问正常。

看起来确实是这个原因，你的本地或远程 ip 被标记了，即便是正常的 https 请求也会被干扰。可以尝试更换一下 ip。

**Comment by 3andne** [comment]
> 尝试给IP分了一个域名，用chrome浏览器https://域名去访问，同样发生了阻断。

@moranno 听上去你的测试方法是错的。如果你给你的shadowtls服务器分配了一个域名并用这个域名去访问它，而这个这个服务器表演的握手是其他网站（比如bing.com)，那浏览器一定会因为返回回来了bing.com的证书而拒绝连接。
如果你想有效地测试，你应该改你本地的hosts文件。

**Comment by moranno** [comment]
> > 尝试给IP分了一个域名，用chrome浏览器[https://域名去访问，同样发生了阻断。](https://%E5%9F%9F%E5%90%8D%E5%8E%BB%E8%AE%BF%E9%97%AE%EF%BC%8C%E5%90%8C%E6%A0%B7%E5%8F%91%E7%94%9F%E4%BA%86%E9%98%BB%E6%96%AD%E3%80%82)
> 
> @moranno 听上去你的测试方法是错的。如果你给你的shadowtls服务器分配了一个域名并用这个域名去访问它，而这个这个服务器表演的握手是其他网站（比如bing.com)，那浏览器一定会因为返回回来了bing.com的证书而拒绝连接。 如果你想有效地测试，你应该改你本地的hosts文件。

今天我又同时测试了浏览器访问和客户端访问，均不再发生阻断了。估计会开完墙降低了吧...

另外，我在host中绑定www.bing.com指向我VPS的IP，通过浏览器访问www.bing.com，竟然能正常使用bing的所有搜索，这个正常不？我的理解是与www.bing.com只是初次tls握手，并不会实际传输bing的数据。那为啥可以正常使用bing ?

**Comment by RPRX** [comment]
@moranno 你之前所描述的“阻断”，该不会是你用 https://IP 访问服务器不通就认为是被阻断了吧。。。

**Comment by moranno** [comment]
@RPRX 当然不是，我没那么小白...毕竟也是有CCNP的人...
我说的阻断是ping不通，具体情况你看我这里发的图片：https://github.com/XTLS/Xray-core/issues/1767#issuecomment-1463457006

另外今天reality也不再阻断了...

**Comment by RPRX** [comment]
@moranno 还是有点白的...比如说，你改了 hosts 后浏览器还能用 www.bing.com 是正常的，不能用才是不正常

你需要实际研究一下这些协议的原理，~~然后就会发现你的很多猜测都是错的~~

**Comment by moranno** [comment]
@RPRX 
虚心请教，能否从底层/协议/包头等原因大致猜测/解释一下我昨天遇到的问题？
为啥使用自己域名的vless/trojan可以正常使用，而shadowtls和reality会产生阻断？

> 选的 dest 不合适

我dest选的都是支持TLS1.3的网站，包括bing,ted,lovelive,以及 https://github.com/ihciah/shadow-tls/wiki/V3-Protocol 这里推荐的。

**Comment by moranno** [comment]
> 本地/远端 ip 命中标记后可能会有干扰，可以试着强制解析域名到你的 ip，然后测试是否浏览器访问正常。

基本可以确定是本地IP导致的干扰，我在相同的网络环境下，通过在光猫多播获取新IP后，阻断问题消失。再切换到老IP，继续引发阻断。

但我不理解的是：为何会产生阻断和干扰？
为何使用自己域名的vless/trojan可以正常使用，而shadowtls和reality会产生阻断(IP无法ping通3分钟)？

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/discussions/1772

2月底3月初陆续有网友反映类似的现象
