### ISSUE TITLE
如果使用Shadow-TLS访问非https的网站会怎么样？是否会存在安全隐患

### ISSUE THREAD

**Issue by augumn** [ihciah/shadow-tls#79]
因为Shadow-TLS自身不带证书，握手之后发送的数据包是明文

**Comment by ihciah** [comment]
主动探测以及流量劫持当前已经通过v3协议解决；tls指纹和流量特征等后续计划暴露可配置接口来修改。

augumn ***@***.***> 于2023年3月13日周一 17:06写道：
