### ISSUE TITLE
也就是说，本项目只是多了一个tls握手，流量本身是不加密的？

### ISSUE THREAD

**Issue by aa51513** [ihciah/shadow-tls#8]
仔细看了一下源码，发现流量本身是不加密的？
不自签证书替代一下？

**Comment by aa51513** [comment]
> 是的，设计上就是如此。本来就是封装别的proxy的数据，所以没必要再做一层。

感谢回答解惑，另外感谢提供这个不错的工具。

**Comment by ihciah** [comment]
https://www.ihcblog.com/a-better-tls-obfs-proxy/
