### ISSUE TITLE
shadow-tls连通性问题

### ISSUE THREAD

**Issue by LucaLin233** [ihciah/shadow-tls#82]
问题：Surge策略组中点击测试延迟始终显示超时
设备：Surge
确认过ss-rust的端口和shadow-tls的端口都没有被墙，以及二者的docker日志，均正常（shadowtls日志都是显示和我本地的ip建立连接完成），shadow-tls使用的是v2版本，请问还能是什么问题导致的连接超时？

ss-rust compose：

  shadowsocks:
    image: teddysun/shadowsocks-rust:latest
    container_name: ss-rust
    restart: always
    network_mode: host
    volumes:
      - ./ss-config:/etc/shadowsocks-rust
      - 
shadowtls compose：

  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    container_name: shadow-tls
    restart: always
    network_mode: host
    environment:
      - MODE=server
      - LISTEN=0.0.0.0:8443
      - SERVER=127.0.0.1:ss端口
      - TLS=www.bing.com:443
      - PASSWORD=密码

服务端重启过后连接正常，但已经出现过好几次
目前添加 RUST_LOG=error 来记录日志观察会不会返回原因（这种做法是否正确？）

**Comment by ihciah** [comment]
可以排查下是不是fd到limit了。

**Comment by LucaLin233** [comment]
> RUST_LOG=er

> 可以排查下是不是fd到limit了。

额我个人是linux新手，请问这个fd到limit是什么意思，抱歉（

**Comment by LucaLin233** [comment]
> Check [memlock](https://github.com/bytedance/monoio/blob/master/docs/en/memlock.md) as ihciah has already written about [it](https://github.com/ihciah/shadow-tls#note).

It is already unlimited

**Comment by LucaLin233** [comment]
> What is the output of `cat /proc/sys/fs/file-nr` command? (specially in outage time)

992     0       9223372036854775807, is this correct?
