### ISSUE TITLE
相同配置情况下一台vps v3 无法建立连接

### ISSUE THREAD

**Issue by AmiasWayne** [ihciah/shadow-tls#84]
相同服务器端配置 新加坡小鸡没问题 美国的小鸡连不通。
检查了一下端口情况美国的小鸡只能监听 没有建立连接
使用的是docker-compose的方法。
烦请大佬帮忙给个排障方向 感谢🫡🫡

**Comment by AmiasWayne** [comment]
补充：关掉配置里面有v3=1回退到v2 再去检查端口情况就发现有连接的一行

**Comment by ihciah** [comment]
1. 通用办法：log level 调成 debug 然后看有没有什么报错
2. 和协议版本有关：怀疑是否都开启了 v3
3. 和地区有关：看下你使用的握手服务器是不是在某个地区不支持 TLS1.3 而在另一个地区支持（比如 cloud.tencent.com 就这样）

**Comment by AmiasWayne** [comment]
> 1. 通用办法：log level 调成 debug 然后看有没有什么报错
> 
> 2. 和协议版本有关：怀疑是否都开启了 v3
> 
> 3. 和地区有关：看下你使用的握手服务器是不是在某个地区不支持 TLS1.3 而在另一个地区支持（比如 cloud.tencent.com 就这样）
> 
> 4. 机器问题：`curl --resolve example.com:443:1.2.3.4 https://example.com:443 -vvv` 预期能显示 example.com 对应的内容，如果没有可以怀疑下防火墙等配置（example.com 是你的握手服务器, 443 是你的监听端口, 1.2.3.4 是你的小鸡 ip）

多谢大佬 已搞定🫡🫡🫡
