### ISSUE TITLE
提问：https://www.infineon.de握手？

### ISSUE THREAD

**Issue by univerioiln233** [ihciah/shadow-tls#92]
和https://www.infineon.de握手，会跟哪一个ip握手呢？。是vps 就近 和https://www.infineon.de握手？

**Comment by univerioiln233** [comment]
感觉s-t的延迟好慢，慢一倍。就近握手的话，延迟 就接近 本来的延迟 了？

**Comment by ihciah** [comment]
TLS 握手本来就慢，但是只有建立连接的延迟较高。可以考虑选用离 vps 较近的握手服务器，以及尽可能使用 TLS1.3。
